<?php

namespace App\Repository;

/**
 * AbstractTypeOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractTypeOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
