<?php

namespace App\Repository;

/**
 * CompteBanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteBanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
